services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapeamento de porta para acesso externo

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    command: rails server -b 0.0.0.0  # Adicionando o binding para 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  db_data:





