# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: notification.proto for package 'notification'

require 'grpc'
require_relative 'notification_pb'


  module NotificationServicePb
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'NotificationPb.NotificationServicePb'

      rpc :SendWebscrapingNotification, ::NotificationPb::WebscrapingNotificationRequest, ::NotificationPb::NotificationResponse
    end

    Stub = Service.rpc_stub_class
  end

