# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: web_scraping.proto for package 'webscraping'

require 'grpc'
require_relative '../lib/web_scraping_pb'
require_relative '../app/repositories/scraped_data_repository'

module Webscraping
  module WebScrapingService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'webscraping.WebScrapingService'

      rpc :ScrapeData, ::Webscraping::ScrapeRequest, ::Webscraping::ScrapeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
